### ISSUE TITLE
How do I change the port?

### ISSUE THREAD

**Issue by MensoMG** [OpenPrinting/ps-printer-app#10]
What if I have a server running on port 8000? How do I change to another port?

**Comment by tillkamppeter** [comment]
If you server is already running and you start the Printer Application, it will start on port 8001. Only if yout server starts after the Printer Application, it will not be able to start or has to take an alternative port.

At least some Printer Applications can be started with an alternative port:
```
ps-printer-app -o server-port=10000 server
```
What we need is some way to set the default port of the Printer Application by a configuration file.
