### ISSUE TITLE
Unable to use that driver

### ISSUE THREAD

**Issue by MensoMG** [OpenPrinting/ps-printer-app#11]
1. I can not add the printer Kyocera FS-1020MFP
![image](https://user-images.githubusercontent.com/67746828/186945007-eac30cb1-ea42-4665-b172-46048958504d.png)

in the log says "No format found for printing in streaming mode", but in my opinion, this is too unclear information for the end user

4. What is wrong with the [ppd file](https://gist.github.com/MensoMG/bfd7f9d1883e5eb088e0df222dcdee5e):

6. The [log ](https://gist.github.com/MensoMG/176034f0c5872544421aa00bc752156b)shows "PPD /var/snap/ps-printer-app/common/ppd//Kyocera-FS-1020MFP-.ppd: Missing PPD-Adobe-4.x header on line 0", but it is set. 

7. Also in the [log](https://gist.github.com/MensoMG/176034f0c5872544421aa00bc752156b) "Unable to register printer, is the Avahi daemon running?", I have already started it

What should I do? Before [this](https://github.com/OpenPrinting/cups/issues/103) edit, everything worked fine for me.

**Comment by tillkamppeter** [comment]
Thanks for the bug report.

I assume that you tried to add a PPD file of a printer which the PostScript Printer Application Snap does not already support by itself. Am I right? Can you attach the PPD file then (rename it to have a `.txt` file extension, for GitHub to accept it).

Could you please upload you screenshot directly to this GitHub issue? Please avoid **whenever possible** any commercial third-party hosting services. They are overloaded with ads, your files often do not download, but only the ads, files will not stay there forever, making our issues ununderstandable and not staying a knowledge base.

**Comment by tillkamppeter** [comment]
I have found a bug with Kyocera PPDs in the PostScript Printer Application and [fixed it in cups-filters](https://github.com/OpenPrinting/cups-filters/commit/c71879afd). I do not know whether it also has caused your problem. Please try again with the PostScript Printer Application as it is in the Snap Store now.

**Comment by MensoMG** [comment]
It is a pity I no longer have the printer (and I reinstalled the OS a long time ago too), I hope people with the same printer will try to reproduce the problem,

**Comment by tillkamppeter** [comment]
Bug most probably already fixed, OP does not have this printer any more. Closing ...

**Comment by lslatr23** [comment]
[root@ploplinux pappl-retrofit]# legacy-printer-app server
E [2024-06-13T16:49:23.758Z] libppd: [PPD Collections] /usr/lib/cups/driver/driverless: Unable to execute ippfind utility: No such file or directory
E [2024-06-13T16:50:11.168Z] No format found for printing in streaming mode

![image](https://github.com/OpenPrinting/ps-printer-app/assets/134659590/77e7f7ac-f03d-45e0-bb82-f5e82e6dff55)
